<div class="alert alert-block alert-success" style="margin-top: 20px"><h1> NumPy</h1>
<code>By AKSHAY KASHYAP</code></div>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
#defining array using numpy 

a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
# shape (row, col)
a.shape

(4,)

In [6]:
# total element i.e. row*col
a.size

4

In [7]:
# know dimension
a.ndim

1

In [8]:
# type v/s dtype
type(a)

#ndarray => n dimension array

numpy.ndarray

In [9]:
#type v/s dtype
a.dtype

#dtype => data type

dtype('int32')

In [10]:
f = np.array([2.5, 1.3, 2.7])

In [11]:
type(f)

numpy.ndarray

In [12]:
f.dtype

dtype('float64')

<div class="alert alert-block alert-info" style="margin-top: 20px"><H2>access array</H2></DIV>

In [13]:
a[0] # a[]

1

In [14]:
a[1:3] # a[start, end] ; end is exclude

array([2, 3])

In [15]:
#assigning new value
a[0]=9

In [16]:
a

array([9, 2, 3, 4])

In [17]:
#can't assign different datatype
a[3]=7.5

# only 7 will be assign instead of 7.5

In [18]:
a

array([9, 2, 3, 7])

In [19]:
f

array([2.5, 1.3, 2.7])

In [20]:
f[2]=5
# 5 will be store in float (5. )   

In [21]:
f

array([2.5, 1.3, 5. ])

In [22]:
# maxmium in an array
a.max()

9

In [23]:
# minimum in an array
a.min()

2

<div class="alert alert-block alert-info" style="margin-top: 20px"><h2>2D array</h2></div>

In [24]:
a2 = np.array([[1,2,22],[5,7,9],[2,36,7]])   #np.array([[]]) , 2 square bracket = 2D

In [25]:
a2

array([[ 1,  2, 22],
       [ 5,  7,  9],
       [ 2, 36,  7]])

In [26]:
a2.shape

(3, 3)

In [27]:
a2.size

9

In [28]:
a2.ndim # dimension

2

In [29]:
type(a2)

numpy.ndarray

In [30]:
a2.dtype

dtype('int32')

<div class="alert alert-block alert-success" style="margin-top: 20px"><h2>accessing 2D element</h2></div>

In [31]:
a2

array([[ 1,  2, 22],
       [ 5,  7,  9],
       [ 2, 36,  7]])

<hr>
let's , I wanna print 36 , so row : 2 , col : 1 <hr>

In [32]:
a2[2,1] # a2[row,col]

36

In [33]:
a2[1:3,0:2] # 0:2 means only 2 not included (only 0,1)

array([[ 5,  7],
       [ 2, 36]])

In [34]:
a2[[0,2],1:3]
# row (0, 2 only)
# col (1 to 2 ; 3 excluded )

array([[ 2, 22],
       [36,  7]])

<hr><div><h2><code>arange</code>, <code>reshape</code> and <code>linspace</code> </h2></div><hr>

In [35]:
a = np.arange(10) # create array 0 to 9 in 1D only

In [36]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,10,2) # (start,end,step)

array([2, 4, 6, 8])

In [38]:
a.reshape(2,5) # reshaping in 2D (2 rows, 5 columns)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
np.arange(12).reshape(3,4) # creating array and reshaping in single line

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<hr>linspace (linear space) create a number line and divide in No. of value we need<hr>

In [40]:
np.linspace(0,10,5) # (start,end, number_of_value_we_need) [start and end both are inclusive]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
# similarly logspace (logrithimic space)
np.logspace(0,50,5)

array([1.00000000e+00, 3.16227766e+12, 1.00000000e+25, 3.16227766e+37,
       1.00000000e+50])