<div class="alert alert-block alert-info" style="margin-top: 20px"><h1> NumPy</h1>
<code>By AKSHAY KASHYAP</code></div>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
data= np.loadtxt('numpy_data/wind.data')

In [4]:
data.shape

(6574, 15)

In [5]:
data

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

<div class="alert alert-success alert-danger" style="margin-top: 20px">
    The first three columns are year, month and day.<br>
The remaining 12 columns are average windspeeds in knots<br> 
at 12 locations in Ireland on that day.</div>


<hr> <div class="alert alert-block alert-info" style="margin-top: 20px">
    1)Let's separarte date and speed</div><hr>

In [6]:
date = data[:,:3] # selecting all rows, 3 columns
speed = data[:,3:] # selecting all rows, except 3 columns

In [7]:
date[:5]

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.],
       [61.,  1.,  4.],
       [61.,  1.,  5.]])

In [8]:
speed[:3]

array([[15.04, 14.96, 13.17,  9.29, 13.96,  9.87, 13.67, 10.25, 10.83,
        12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83,  6.5 , 12.62,  7.67, 11.5 , 10.04,  9.79,
         9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, 10.13, 11.17,  6.17, 11.25,  8.04,  8.5 ,
         7.67, 12.75, 12.71]])

<hr><div class="alert alert-block alert-info" style="margin-top: 20px">
2) Calculate the min, max and mean windspeeds and standard deviation of the <br>
windspeeds over all the locations and all the times (a single set of numbers <br>
for the entire dataset).</div><hr>

In [9]:
speed.min()

0.0

In [10]:
speed.max()

42.54

In [11]:
speed.mean()

10.22837377040868

In [12]:
speed.std()

5.603840181095793

<hr><div class="alert alert-block alert-info" style="margin-top: 20px">
    3) Calculate the min, max and mean windspeeds and standard deviations of the<br>
windspeeds at each location over all the days (a different set of numbers<br>
for each location)</div><hr>

In [13]:
speed.min(axis = -2) # row , also axis = 0

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [14]:
speed.max(axis = 0) # row , also axis = -2

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [15]:
speed.mean(axis = 0)

array([12.36371463, 10.64644813, 11.66010344,  6.30627472, 10.45688013,
        7.09225434,  9.7968345 ,  8.49442044,  8.49581838,  8.70726803,
       13.121007  , 15.59946152])

In [16]:
speed.std(axis = 0)

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

<hr><div class="alert alert-block alert-info" style="margin-top: 20px">
    4) Calculate the min, max and mean windspeed and standard deviations of the<br>
   windspeeds across all the locations at each day (a different set of numbers<br>
   for each day)</div><hr>

In [17]:
speed.min(axis = 1)

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [18]:
speed.max(axis = 1).shape
# speed.mean(axis = 1)
# speed.std(axis = 1)

(6574,)

<hr><div class="alert alert-block alert-info" style="margin-top: 20px">
5) Find the location which has the greatest windspeed on each day<br>
(an integer column number for each day).</div><hr>

In [19]:
speed.argmax(axis = 1)

array([10, 10,  0, ..., 11, 11,  2], dtype=int64)

<hr>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    6) Find the year, month and day on which the greatest windspeed was recorded.
</div><hr>

In [20]:
np.where(speed == speed.max())

(array([2161], dtype=int64), array([11], dtype=int64))

In [21]:
#or
m = speed.max(axis=1).argmax()
print(m)

2161


In [22]:
date[m,:] #row from previous data

array([66., 12.,  2.])

<hr><div class="alert alert-block alert-info" style="margin-top: 20px">
    7) Find the average windspeed in January for each location.</div><hr>

In [23]:
jan = date[:,1]==1  # Creating a boolean mask for January

jan

array([ True,  True,  True, ..., False, False, False])

In [24]:
jan_speed = speed[jan]  # Filtering speeds for January
avg_windspeeds_jan = jan_speed.mean(axis=0)  # Computing mean windspeeds for January

print(avg_windspeeds_jan)

[14.86955197 12.92166667 13.29962366  7.19949821 11.67571685  8.05483871
 11.81935484  9.5094086   9.54320789 10.05356631 14.55051971 18.02876344]
