<div class="alert alert-block alert-info" style="margin-top: 20px"><h1> NumPy</h1>
<code>By AKSHAY KASHYAP</code></div>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

<hr> <div class="alert alert-block alert-danger" style="margin-top: 20px">
    <h3>Random</h3></div><hr>

_________
### rand
__________
Generates random numbers from a uniform distribution over [0, 1).

In [3]:
# Generate a single random float
random_float = np.random.rand()
print(random_float)

# Generate a 2x3 array of random floats
random_array = np.random.rand(2, 3)
print(random_array)

0.37933134515094924
[[0.63805235 0.18025859 0.58580086]
 [0.10458389 0.50919446 0.71525344]]


______
### randn
______
Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [4]:
# Generate a single random number from a standard normal distribution
random_number = np.random.randn()
print(random_number)

# Generate a 2x3 array of random numbers from a standard normal distribution
random_array = np.random.randn(2, 3)
print(random_array)

0.12004775685083968
[[-0.48111859 -0.41708228  0.75108247]
 [-0.21242552 -0.82030027  0.64890583]]


_________
### randint
______
Generates random integers within a specified range.

In [5]:
# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_integer = np.random.randint(0, 10)
print(random_integer)

# Generate a 2x3 array of random integers between 0 and 50 (exclusive)
random_array = np.random.randint(0, 50, size=(2, 3))
print(random_array)

6
[[18 45 41]
 [48 25  1]]


________
### uniform
_____
Generates random numbers from a uniform distribution over [low, high).

In [6]:
# Generate a single random float between 1 and 10
random_float = np.random.uniform(1, 10)
print(random_float)

# Generate a 2x3 array of random floats between 1 and 10
random_array = np.random.uniform(1, 10, size=(2, 3))
print(random_array)

5.607181237260918
[[5.69842999 2.15001212 1.51726729]
 [4.939598   8.38485497 6.65930334]]


________
### normal
_______
Generates random numbers from a normal distribution with a specified mean and standard deviation.

In [7]:
# Generate a single random number from a normal distribution with mean 0 and standard deviation 1
random_number = np.random.normal(loc=0, scale=1)
print(random_number)

# Generate a 2x3 array of random numbers from a normal distribution with mean 5 and standard deviation 2
random_array = np.random.normal(loc=5, scale=2, size=(2, 3))
print(random_array)

-0.1449251030363972
[[1.66000734 2.92422924 1.87411706]
 [6.51932584 7.72785747 5.01971513]]


__________
### binomial
________
Generates random numbers from a binomial distribution.

In [8]:
# Generate a single random number from a binomial distribution with 10 trials and probability 0.5
random_number = np.random.binomial(n=10, p=0.5)
print(random_number)

# Generate a 2x3 array of random numbers from a binomial distribution with 10 trials and probability 0.5
random_array = np.random.binomial(n=10, p=0.5, size=(2, 3))
print(random_array)

8
[[6 6 5]
 [5 8 8]]


___________
### poisson
_______
Generates random numbers from a Poisson distribution.

In [9]:
# Generate a single random number from a Poisson distribution with lambda (rate) 3
random_number = np.random.poisson(lam=3)
print(random_number)

# Generate a 2x3 array of random numbers from a Poisson distribution with lambda (rate) 3
random_array = np.random.poisson(lam=3, size=(2, 3))
print(random_array)

2
[[2 5 1]
 [1 4 3]]


_________
### choice
________
Generates random samples from a given 1-D array.

In [10]:
# Randomly choose a single element from the array
random_choice = np.random.choice([1, 2, 3, 4, 5])
print(random_choice)

# Randomly choose 3 elements from the array with replacement
random_choices = np.random.choice([1, 2, 3, 4, 5], size=3, replace=True)
print(random_choices)

# Randomly choose 3 elements from the array without replacement
random_choices = np.random.choice([1, 2, 3, 4, 5], size=3, replace=False)
print(random_choices)

1
[2 3 3]
[4 5 3]


_______
### shuffle
________
Randomly permutes a sequence or array in place.

In [11]:
# Shuffle a 1-D array
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)

# Shuffle each row of a 2-D array independently
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.random.shuffle(array_2d)
print(array_2d)

[3 4 2 1 5]
[[1 2 3]
 [4 5 6]]
